export const dropDownList = [
  {
    mainjobID: 1,
    mainjob: '직군 전체',
    subjob: [
      { id: 1, category: '개발 전체' },
      { id: 2, category: '웹 개발자' },
      { id: 3, category: '서버 개발자' },
      { id: 4, category: '프론트엔드 개발자' },
      { id: 5, category: '소프트웨어 엔지니어' },
      { id: 6, category: '자바 개발자' },
      { id: 7, category: '안드로이드 개발자' },
      { id: 8, category: 'iOS 개발자' },
      { id: 9, category: 'Node.js 개발자' },
      { id: 10, category: 'C, C++ 개발자' },
      { id: 11, category: '데이터 엔지니어' },
      { id: 12, category: '파이썬 개발자' },
      { id: 13, category: 'DevOps / 시스템 개발자' },
      { id: 14, category: '시스템, 네트워크 관리자' },
      { id: 15, category: '머신러닝 엔지니어' },
      { id: 16, category: '데이터 사이언티스트' },
      { id: 17, category: '빅데이터 엔지니어' },
      { id: 18, category: '기술지원' },
      { id: 19, category: '개발 매니저' },
      { id: 20, category: 'QA, 테스트 엔지니어' },
    ],
  },
  {
    mainjobID: 2,
    mainjob: '개발',
    subjob: [
      { id: 1, category: '개발 전체' },
      { id: 2, category: '웹 개발자' },
      { id: 3, category: '서버 개발자' },
      { id: 4, category: '프론트엔드 개발자' },
      { id: 5, category: '소프트웨어 엔지니어' },
      { id: 6, category: '자바 개발자' },
      { id: 7, category: '안드로이드 개발자' },
      { id: 8, category: 'iOS 개발자' },
      { id: 9, category: 'Node.js 개발자' },
      { id: 10, category: 'C, C++ 개발자' },
      { id: 11, category: '데이터 엔지니어' },
      { id: 12, category: '파이썬 개발자' },
      { id: 13, category: 'DecOps / 시스템 개발자' },
      { id: 14, category: '시스템, 네트워크 관리자' },
      { id: 15, category: '머신러닝 엔지니어' },
      { id: 16, category: '데이터 사이언티스트' },
      { id: 17, category: '빅데이터 엔지니어' },
      { id: 18, category: '기술지원' },
      { id: 19, category: '개발 매니저' },
      { id: 20, category: 'QA, 테스트 엔지니어' },
    ],
  },
  {
    mainjobID: 3,
    mainjob: '경영·비즈니스',
    subjob: [
      { id: 1, category: '경영·비즈니스 전체' },
      { id: 2, category: '서비스 기획자' },
      { id: 3, category: 'PM·PO' },
      { id: 4, category: '사업개발·기획자' },
      { id: 5, category: '전략 기획자' },
      { id: 6, category: '경영지원' },
      { id: 7, category: '운영 매니저' },
      { id: 8, category: '회계·경리' },
      { id: 9, category: '데이터 분석가' },
      { id: 10, category: '총무' },
      { id: 11, category: '자금담당' },
      { id: 12, category: '해외 사업개발·기획자' },
      { id: 13, category: '컨설턴트' },
      { id: 14, category: '상품기획자(BM)' },
      { id: 15, category: '조직관리' },
      { id: 16, category: '오피스 관리' },
      { id: 17, category: '사무보조' },
      { id: 18, category: '구매담당' },
      { id: 19, category: '정보보호 담당자' },
      { id: 20, category: '경영 혁신가' },
    ],
  },
  {
    mainjobID: 4,
    mainjob: '마케팅·광고',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 5,
    mainjob: '디자인',
    subjob: [
      { id: 1, category: '디자인 전체' },
      { id: 2, category: 'UX 디자이너' },
      { id: 3, category: 'UI, GUI 디자이너' },
      { id: 4, category: '웹 디자이너' },
      { id: 5, category: '그래픽 디자이너' },
      { id: 6, category: '모바일 디자이너' },
      { id: 7, category: 'BI/BX 디자이너' },
      { id: 8, category: '광고 디자이너' },
      { id: 9, category: '제품 디자이너' },
      { id: 10, category: '영상, 모션 디자이너' },
      { id: 11, category: '3D 디자이너' },
      { id: 12, category: '패키지 디자이너' },
      { id: 13, category: '캐릭터 디자이너' },
      { id: 14, category: '일러스트레이터' },
      { id: 15, category: '2D 디자이너' },
      { id: 16, category: '아트 디렉터' },
      { id: 17, category: '공간 디자이너' },
      { id: 18, category: '출판, 편집 디자이너' },
      { id: 19, category: '패션 디자이너' },
      { id: 20, category: '인테리어 디자이너' },
    ],
  },
  {
    mainjobID: 6,
    mainjob: '영업',
    subjob: [
      { id: 1, category: '영업 전체' },
      { id: 2, category: '기업영업' },
      { id: 3, category: '영업 관리자' },
      { id: 4, category: '기술영업' },
      { id: 5, category: '주요고객사 담당자' },
      { id: 6, category: '해외영업' },
      { id: 7, category: '솔루션 컨설턴트' },
      { id: 8, category: '고객성공매니저' },
      { id: 9, category: '미디어 세일즈' },
      { id: 10, category: '세일즈 엔지니어' },
      { id: 11, category: '내부영업' },
      { id: 12, category: '의료기기 영업' },
      { id: 13, category: '제약영업' },
    ],
  },
  {
    mainjobID: 7,
    mainjob: '고객서비스·리테일',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 8,
    mainjob: '게임 제작',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 9,
    mainjob: 'HR',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 10,
    mainjob: '미디어',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 11,
    mainjob: '금융',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 12,
    mainjob: '엔지니어링·설계',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 13,
    mainjob: '물류·무역',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 14,
    mainjob: '제조·생산',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 15,
    mainjob: '의료·제약·바이오',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 16,
    mainjob: '교육',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 17,
    mainjob: '법률·법집행기관',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 18,
    mainjob: '식·음료',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
    ],
  },
  {
    mainjobID: 19,
    mainjob: '건설·시설',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
  {
    mainjobID: 20,
    mainjob: '공공·복지',
    subjob: [
      { id: 1, category: '마케팅·광고 전체' },
      { id: 2, category: '마케터' },
      { id: 3, category: '디지털 마케터' },
      { id: 4, category: '콘텐츠 마케터' },
      { id: 5, category: '퍼포먼스 마케터' },
      { id: 6, category: '마케팅 전략 기획자' },
      { id: 7, category: '브랜드 마케터' },
      { id: 8, category: '광고 기획자(AE)' },
      { id: 9, category: '글로벌 마케팅' },
      { id: 10, category: '소셜 마케터' },
      { id: 11, category: '그로스 해커' },
      { id: 12, category: '모바일마케팅' },
      { id: 13, category: 'PR 전문가' },
      { id: 14, category: '카피라이터' },
      { id: 15, category: '마케팅 디렉터' },
    ],
  },
];
