export const subMenuDownList = [
  { id: 1, category: '개발 전체' },
  { id: 2, category: '웹 개발자' },
  { id: 3, category: '서버 개발자' },
  { id: 5, category: '프론트엔드 개발자' },
  { id: 6, category: '소프트웨어 엔지니어' },
  { id: 7, category: '자바 개발자' },
  { id: 8, category: '안드로이드 개발자' },
  { id: 9, category: 'iOS 개발자' },
  { id: 10, category: 'Node.js 개발자' },
  { id: 11, category: 'C, C++ 개발자' },
  { id: 12, category: '데이터 엔지니어' },
  { id: 13, category: '파이썬 개발자' },
  { id: 14, category: 'DecOps / 시스템 개발자' },
  { id: 15, category: '시스템, 네트워크 관리자' },
  { id: 16, category: '머신러닝 엔지니어' },
  { id: 17, category: '데이터 사이언티스트' },
  { id: 18, category: '빅데이터 엔지니어' },
  { id: 19, category: '기술지원' },
  { id: 20, category: '개발 매니저' },
  { id: 21, category: 'QA, 테스트 엔지니어' },
];
